### PR TITLE
Add `--export-attachments-output` CLI option

### PR DESCRIPTION
**Pull request by matteocargnelutti**
This new option allows for exporting attachments (generated exchanges) to a given directory at the end of the capture process.

### CODE REVIEW

**Review by rebeccacremona — COMMENTED** [review]
Sweet! 

What's the best way to know in advance what the filenames will be?

**Comment by matteocargnelutti** [comment]
> Sweet!
> 
> What's the best way to know in advance what the filenames will be?

@rebeccacremona  That's an excellent question.
**I am not sure about "in advance" but:**
- The CLI tells you which files it wrote
- The JSON summary list generated exchanges (attachments) 

The filenames can be predicted to a certain extent, and we can certainly document that.
- All certs are `*.pem`
- Screenshot is always `screenshot.png`
- PDF Snapshot is always `pdf-snapshot.pdf`
- Videos are always `video-extracted-x.mp4`, subtitles `video-extracted-x.LOCALE.vtt`
- Etc ...

At the moment, this is documented at codebase-level ([example 1](https://github.com/harvard-lil/scoop/blob/main/options.types.js#L6), [example 2](https://github.com/harvard-lil/scoop/blob/main/Scoop.js#L816))

The CLI `--help` menu is already pretty much maxed out with info 😅 . Maybe we could summarize that info in README?

**Comment by rebeccacremona** [comment]
Thanks!!

> The CLI `--help` menu is already pretty much maxed out with info 😅 . Maybe we could summarize that info in README?

That sounds good! I think with my current setup, so long as I know the file extensions to look for in advance, I can programmatically find the specific artifact I'm looking for! Or, if in summary.json, `echangeUrls` were a dict with keys `webCapture`, `screenshot`, `provenanceSummary`, `certs`, etc. instead of a list?
```
"exchangeUrls": [
    "https://example.com/",
    "file:///screenshot.png",
    "file:///example.com.pem",
    "file:///provenance-summary.html"
  ]
```

**Comment by matteocargnelutti** [comment]
@rebeccacremona I added a separate `attachments` property to the object the JSON capture summary feature generates, as discussed, let me know what you think 😄.

**Review by rebeccacremona — APPROVED** [review]
Love it

**Pull request merged**
